"""
Imposter
March 6th - Version 1.0: basic skeleton
March 7th - Version 1.1: added game logic for game.html
March 12th - Version 1.2: environment key set
March 23rd - Version 1.3: Successful connection with AI
March 25th - Version 1.4: Debugging the issue with the Gemini server not responding
March 30th - Version 1.5: Added environment variables to ensure security
"""




from flask import Flask, render_template, request, redirect, url_for
from google import genai
from google.genai import types
import os
import json
import random
from rules import Rules #import rules class




rules = Rules()





CATEGORIES = ["Food", "Animal", "Location"]  # Example categories
AI_MODELS = ["gemini-3.1-flash-lite-preview", "gemini-2.5-flash-lite", "gemini-2.0-flash-lite"]


app = Flask(__name__)

KEY = os.environ.get("KEY")


client = genai.Client(api_key=KEY) #replace with actual API




# Check token usage(not used currently)
"""
total_tokens = client.models.count_tokens(
    model = "gemini-3.1-flash-lite-preview",
    contents =
)
"""




#Call function to prompt gemini
def gemini(cat):
    i = 0
    response = None
    while i < len(AI_MODELS) and response is None: #try different models if the first one fails
        response = client.models.generate_content(
            model = AI_MODELS[i],
            contents = ("Given the following categories provided, randomly select one of the categories, then generate a random word that relates to one of them."
                "Based off of that generated word, generate a list of 5 hint words that relate to the word. Make sure that the hint words do not contain the original word in itself,"
                "or is a direct synonym of it. The hint words should not be too obvious such that the first instinctual connection is to the original word."
            "The original word does not necessarily have to be one singular word, but must be a single object, or concept, or place. The generated words must not exceed a length of 3 words. "
            "The hint words must be 1 word in length. "
            f"Respond with only the generated words in a string, no other words, with each separated with a comma. The categories are {', '.join(cat)}"
            )#sectioned into different lines for readability, the local var cat is sent to the AI for word generation
        )
        print(response.text) #debug
        i +=1
    if response is None:
        raise Exception("All AI models failed to generate a response") #if all models fail, raise an exception to be caught in the index function
    #returns a list and first word is the normal word and second word is the imposter word
    return response.text.split(",") #split the response into two words based on the comma






def chooseimposter(num_of_players, num_of_imposters):
    # Create a list of players
    players = list(range(1, num_of_players + 1))




    # Randomly select imposters
    imposters = random.sample(players, num_of_imposters)




    return imposters












@app.route("/", methods=['GET', 'POST'])
def index():
    categories = CATEGORIES




    if request.method == 'POST':
        # Get the data from the form
        num_of_players = int(request.form['num_of_players'])
        num_of_imposters = int(request.form['num_of_imposters'])
        if num_of_imposters > num_of_players:
            return redirect(url_for('error')) # Redirect to an error page if the number of imposters is greater than the number of players
        imposters = chooseimposter(num_of_players, num_of_imposters)
        player_category_selection = request.form.getlist('category')
        print(f"Player category selection: {player_category_selection}") #debug


        try: #code in case gemini fails to generate words
            word = gemini(player_category_selection)
            setup_data = {
                "num_of_players": num_of_players,
                "num_of_imposters": num_of_imposters,
                "category": player_category_selection,
                "imposters": imposters,
                "normal_word": word[0], # actual word will be generated by gemini
                "imposter_word":word[1], #actual word will be generated by gemini, up to 5 different hint words
                "current_player": 1,
                "current_role": "hidden"
            }
            # We use json.dumps so we can pass it as one string
            return redirect(url_for('player_names', large_string = "fhieujc3it568nuywgyv8ageuhzubimhewhvnuq89egtniougkr87etoutt8wydy5ku6aow864i8yto5yiouysejyteljwehkjasoijheboisudfyjhvaroiysakhdbo8xzfy8u356jlhgq37634986hkf8qe5kjwywk4h5bir6",initial_info=json.dumps(setup_data)))
        except Exception as e:
            return redirect(url_for('error', error=str(e))) # Redirect to an error page if gemini fails to generate words
    return render_template("index.html", categories=categories)




@app.route("/player_names", methods=['GET', 'POST'])
def player_names():
    if request.method == 'POST':
        html_str = request.args.get('initial_info')
        py_dict = json.loads(html_str)
        name_list = []
        for value in request.form.items():
            name_list.append(value[1]) #this is the content
        py_dict['player_names'] = name_list
        return redirect(url_for('game', large_string = "kshbdfhusain5cy87wet67tywo875t8348ug9wyejguygsdutu8t9f87t45ntoti5utv8ft4598nt8gt89et5ne876tnfsegngjhdsfgnhhmeumhoiumhahsdmiuthoey598ynb9y58obn3qoeottgjyoge8gt8nygcygmtgaiuorgtbirgouiogouibdfjgt8", initial_info=json.dumps(py_dict))) #redirect to game page with the same info, we can also change the info if we want to add player names or something like that in the future
    return render_template("player_names.html", game_info_json=request.args.get('initial_info'), game_info=json.loads(request.args.get('initial_info'))) #pass the info from the index page to the player names page so we can use it in the form

#now the dictionary looks like this:
"""
{
    "num_of_players": 5,
    "num_of_imposters": 2,
    "category": ["Food"],
    "imposters": [2, 4],
    "normal_word": "Pizza",
    "imposter_word": "Burger",
    "current_player": 1,
    "current_role": "hidden",
    "player_names": ["Alice", "Bob", "Charlie", "David", "Eve"]
}
"""



@app.route("/game", methods=['GET', 'POST'])
def game():
    if request.method == 'POST':
        action = request.form['action']
        # Get bundled data from form
        dict_str_rep = request.form['game_info']

        #turn it into readable dictionary
        py_dict = json.loads(dict_str_rep)




        #for changing variables in the dictionary
        if action == "Next Player":
            #reset role and word for next player
            py_dict['current_role'] = "hidden"
            py_dict['word'] = ''
            py_dict['current_player'] += 1
        elif action == "Click Me to Reveal Role":
            #detect imposter
            if py_dict['current_player'] in py_dict['imposters']:
                py_dict['current_role'] = "Imposter"
                py_dict['word'] = py_dict['imposter_word']
            else:
                py_dict['current_role'] = "Citizen"
                py_dict['word'] = py_dict['normal_word']
        if action == "See Who'll Start":
            return redirect(url_for('who_start', new_info=json.dumps(py_dict)))
    else:
        #get info from the previous page
        initial_info_str = request.args.get('initial_info')
        #turn it into a dictionary. This is for the rest of the code in this function to be able to read the info
        py_dict = json.loads(initial_info_str)
    #turn the py dictionary back into a string so that the hidden input can send to the html
    html_dict_rep = json.dumps(py_dict)
    return render_template("game.html", game_info_json=html_dict_rep, game_info=py_dict)


@app.route("/who_start", methods=['POST', 'GET'])
def who_start():
    new_info = request.args.get('new_info')
    py_dict = json.loads(new_info)
    py_dict['starting_player'] = random.randint(1, py_dict['num_of_players']) #randomly select a player to start, this is completely random so no hint is given to the players who are trying to find the imposter
    if request.method == 'POST':
        return redirect(url_for('voting', new2_info=json.dumps(py_dict)))
    return render_template("who_start.html", game_info=py_dict)

#now the dictionary looks like this:
"""
{
    "num_of_players": 5,
    "num_of_imposters": 2,
    "category": ["Food"],
    "imposters": [2, 4],
    "normal_word": "Pizza",
    "imposter_word": "Burger",
    "current_player": 1,
    "current_role": "hidden",
    "player_names": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "starting_player": 3
}
"""


@app.route("/voting", methods=['POST', 'GET'])
def voting():
    new2_info = request.args.get('new2_info')
    py_dict = json.loads(new2_info)
    return render_template("voting.html", game_info=py_dict) #we can use the same info from the previous page since the voting page also needs to know who the players are and stuff like that, we can also change the info if we want to add voting results or something like that in the future


@app.route("/error")
def error():
    if request.args.get('error'):
        error_message = request.args.get('error')
        return render_template("error.html", error=error_message)
    else:
        return render_template("error.html", error="An unknown error occurred. Please try again later.")




if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5001))
    app.run(host='0.0.0.0', port=port, debug=True) #make flask available to the world and set debug to true for development


