"""
Imposter
March 6th - Version 1.0: basic skeleton
March 7th - Version 1.1: added game logic for game.html
"""


from flask import Flask, render_template, request, redirect, url_for
from google import genai
from google.genai import types
import os
import json
import random

CATEGORIES = ["Category 1", "Category 2", "Category 3"]  # Example categories

app = Flask(__name__)


client = genai.Client(api_key = "AIzaSyB36C1zyAp97-SL0RRtbvWJLWeW1rWffR8")

total_tokens = client.models.count_tokens(
    model = "gemini-3.1-flash-lite-preview",
    contents = CATEGORIES
)

def gemini():
    response = client.models.generate_content(
        model = "gemini-3.1-flash-lite-preview",
        contents = CATEGORIES
    )

    return response


def chooseimposter(num_of_players, num_of_imposters):
    # Create a list of players
    players = list(range(1, num_of_players + 1))

    # Randomly select imposters
    imposters = random.sample(players, num_of_imposters)

    return imposters



@app.route("/", methods=['GET', 'POST'])
def index():
    categories = CATEGORIES

    if request.method == 'POST':
        # Get the data from the form
        num_of_players = int(request.form['num_of_players'])
        num_of_imposters = int(request.form['num_of_imposters'])
        if num_of_imposters > num_of_players:
            return redirect(url_for('error')) # Redirect to an error page if the number of imposters is greater than the number of players
        imposters = chooseimposter(num_of_players, num_of_imposters)

        setup_data = {
            "num_of_players": num_of_players,
            "num_of_imposters": num_of_imposters,
            "category": request.form['category'],
            "imposters": imposters, 
            "normal_word": "placeholder1", # actual word will be generated by gemini
            "imposter_word": "placeholder2", #actual word will be generated by gemini
            "current_player": 1,
            "current_role": "hidden",
            "word": ''
        }
        # We use json.dumps so we can pass it as one string
        return redirect(url_for('game', initial_info=json.dumps(setup_data)))
    return render_template("index.html", categories=categories)


@app.route("/game", methods=['GET', 'POST'])
def game():

    if request.method == 'POST':
        action = request.form['action']
        # Get bundled data from form
        dict_str_rep = request.form['game_info']

        #turn it into readable dictionary
        py_dict = json.loads(dict_str_rep)

        #for changing variables in the dictionary
        if action == "Next Player":
            #reset role and word for next player
            py_dict['current_role'] = "hidden"
            py_dict['word'] = ''
            py_dict['current_player'] += 1
        elif action == "Click Me to Reveal Role":
            if py_dict['current_player'] in py_dict['imposters']:
                py_dict['current_role'] = "Imposter"
                py_dict['word'] = py_dict['imposter_word']
            else:
                py_dict['current_role'] = "Citizen"
                py_dict['word'] = py_dict['normal_word']
    else:
        #get info from the url
        initial_info_str = request.args.get('initial_info')
        #turn it into a dictionary
        py_dict = json.loads(initial_info_str)
    #turn the py dictionary back into a string so that the hidden input can send
    html_dict_rep = json.dumps(py_dict)
    return render_template("game.html", game_info_json=html_dict_rep, game_info=py_dict)

@app.route("/error")
def error():
    return render_template("error.html")

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5001))
    app.run(host='0.0.0.0', port=port, debug=True) #make flask available to the world and set debug to true for development
